site_name: zanieng的笔记本
site_url: https://zanieng.github.io/note
repo_name: zanieng/note
repo_url: https://github.com/zanieng/note/

use_directory_urls: false

theme:
  name: material
  language: 'zh'
  icon:
    logo: material/notebook-outline
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - css/tasklist.css
  - css/custom.css
  - css/card.css
  - css/flink.css
  - css/changelog_extra.css

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  #- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - js/katex.js
  #- js/mathjax.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zanieng

plugins:
  - search
  - statistics

nav:
  - Home:
    - index.md
  - computer science:
    - cs/index.md
    - 算法相关:
      - cs/algorithm/index.md
      - ads:
        - cs/algorithm/ads/index.md
        - avl_splay_amortized: cs/algorithm/ads/avl_splay_amortized.md
        - RB-tree_B-tree: cs/algorithm/ads/rb-tree_B-tree.md
        - heap: cs/algorithm/ads/heap.md
        - binomal_queue: cs/algorithm/ads/binomial_queue.md
        - invert file index: cs/algorithm/ads/invert_file_index.md
        - algorithm: cs/algorithm/ads/algorithm.md
      - fds: cs/algorithm/fds/index.md
    - 计算机系统:
      - cs/system/index.md
      - 系统Ⅰ: cs/system/cs1/index.md
      - 系统Ⅱ: 
        - cs/system/cs2/index.md
        - scpu: cs/system/cs2/scpu.md
  - 工具相关: 
    - tools/index.md
    - gdb 命令备忘: tools/gdb.md
    - git,github 命令备忘: tools/git_github.md
