site_name: zanieng的笔记本
site_url: https://zanieng.github.io/note
repo_name: zanieng/note
repo_url: https://github.com/zanieng/note/

theme:
  name: material

nav: 
  - Home:
    - index.md
  - 工具相关: 
    - tools/index.md
    - gdb 命令备忘: tools/gdb.md
    - git,github 命令备忘: tools/git_github.md
